import React from 'react'
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'
import { stripHtmlTags } from '@/lib/offer-template'

const styles = StyleSheet.create({
  page: {
    padding: 60,
    fontFamily: 'Helvetica',
    fontSize: 11,
    lineHeight: 1.6,
    color: '#333333',
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 2,
    borderBottomColor: '#2563eb',
    paddingBottom: 15,
  },
  companyName: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: '#1e40af',
    marginBottom: 4,
  },
  headerSubtext: {
    fontSize: 9,
    color: '#6b7280',
  },
  date: {
    fontSize: 10,
    color: '#6b7280',
    marginBottom: 20,
    textAlign: 'right' as const,
  },
  candidateInfo: {
    marginBottom: 20,
  },
  candidateName: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
  },
  candidateEmail: {
    fontSize: 10,
    color: '#6b7280',
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    color: '#1e40af',
    marginTop: 15,
    marginBottom: 8,
  },
  bodyText: {
    fontSize: 11,
    lineHeight: 1.6,
    marginBottom: 8,
  },
  detailsRow: {
    flexDirection: 'row' as const,
    marginBottom: 6,
  },
  detailLabel: {
    width: 120,
    fontFamily: 'Helvetica-Bold',
    fontSize: 10,
    color: '#6b7280',
  },
  detailValue: {
    flex: 1,
    fontSize: 11,
  },
  footer: {
    position: 'absolute' as const,
    bottom: 40,
    left: 60,
    right: 60,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 10,
  },
  footerText: {
    fontSize: 8,
    color: '#9ca3af',
    textAlign: 'center' as const,
  },
})

interface OfferPDFProps {
  companyName: string
  candidateName: string
  candidateEmail: string
  jobTitle: string
  department: string
  salary: string
  startDate: string
  expiryDate: string
  templateContent: string
  createdDate: string
}

export function OfferPDFDocument({
  companyName,
  candidateName,
  candidateEmail,
  jobTitle,
  department,
  salary,
  startDate,
  expiryDate,
  templateContent,
  createdDate,
}: OfferPDFProps) {
  const plainText = stripHtmlTags(templateContent)
  const paragraphs = plainText.split('\n\n').filter(Boolean)

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Company Header */}
        <View style={styles.header}>
          <Text style={styles.companyName}>{companyName}</Text>
          <Text style={styles.headerSubtext}>Offer of Employment</Text>
        </View>

        <Text style={styles.date}>{createdDate}</Text>

        {/* Candidate Info */}
        <View style={styles.candidateInfo}>
          <Text style={styles.candidateName}>{candidateName}</Text>
          <Text style={styles.candidateEmail}>{candidateEmail}</Text>
        </View>

        {/* Details */}
        <View style={styles.sectionTitle}>
          <Text>Position Details</Text>
        </View>
        <View style={styles.detailsRow}>
          <Text style={styles.detailLabel}>Position:</Text>
          <Text style={styles.detailValue}>{jobTitle}</Text>
        </View>
        {department && (
          <View style={styles.detailsRow}>
            <Text style={styles.detailLabel}>Department:</Text>
            <Text style={styles.detailValue}>{department}</Text>
          </View>
        )}
        <View style={styles.detailsRow}>
          <Text style={styles.detailLabel}>Compensation:</Text>
          <Text style={styles.detailValue}>{salary}</Text>
        </View>
        <View style={styles.detailsRow}>
          <Text style={styles.detailLabel}>Start Date:</Text>
          <Text style={styles.detailValue}>{startDate}</Text>
        </View>
        <View style={styles.detailsRow}>
          <Text style={styles.detailLabel}>Offer Valid Until:</Text>
          <Text style={styles.detailValue}>{expiryDate}</Text>
        </View>

        {/* Body Content */}
        <View style={styles.sectionTitle}>
          <Text>Offer Letter</Text>
        </View>
        {paragraphs.map((paragraph, index) => (
          <Text key={index} style={styles.bodyText}>
            {paragraph.trim()}
          </Text>
        ))}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>
            This offer letter was generated by {companyName}. Confidential.
          </Text>
        </View>
      </Page>
    </Document>
  )
}
